<?php

namespace Modules\Production\Database\seeds;

use Illuminate\Database\Seeder;
use Modules\Production\Models\MachinePart as Model;

class MachinePartSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();
        $data = [
            ['machine_group_id'=>2,'name' => 'Rantai pengantar unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Selenoide valve unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Control valve unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Oil gear box unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Conveyor','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Bearing pompa','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Bearing roll unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Nozel unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Filter unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Sensor baloning unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Level air','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Dozing unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Timing belt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Join coupling unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>2,'name' => 'Rota meter unit','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['machine_group_id'=>8,'name' => 'Motor gear box paliter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Motor gear box roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Piston','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Roll Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Roll Ped','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Motor Blower','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Conveyor 1','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Conveyor 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Conveyor 3','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Steam valve','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Vanbelt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Pintu','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Komputer','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Selang Angin','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'PT 100','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>8,'name' => 'Filter Blower','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['machine_group_id'=>9,'name' => 'Motor gear box paliter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Motor gear box roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Piston','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Roll Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Roll Ped','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Motor Blower','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Conveyor 1','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Conveyor 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Conveyor 3','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Steam valve','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Vanbelt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Pintu','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Komputer','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Selang Angin','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'PT 100','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>9,'name' => 'Filter Blower','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['machine_group_id'=>5,'name' => 'Cigar Bak 1','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Cigar Bak 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Cigar Bak 3','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Cigar Bak 4','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Pompa Bak 1','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Pompa Bak 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Pompa Bak 3','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Pompa Bak 4','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Pompa Sirukulasi Cuka','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Roll Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Roll Padder','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Fixing Roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Swimming Roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Pnematic','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Rantai Penggerak Meja','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Valve Steam','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Ball Valve','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>5,'name' => 'Pompa Sirkulasi Air','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['machine_group_id'=>6,'name' => 'Cigar Bak 1','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Cigar Bak 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Cigar Bak 3','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Cigar Bak 4','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Pompa Bak 1','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Pompa Bak 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Pompa Bak 3','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Pompa Bak 4','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Pompa Sirkulasi Coustic','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Roll Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Roll Pedder','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Fixing Roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Swimming Roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Pneumatic','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Rantai Penggerak Meja','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Valve Steam','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>6,'name' => 'Ball Valve','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['machine_group_id'=>7,'name' => 'Temperatur Setting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'Temperatur Aktual','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'V - Belt Exhaust','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'V - Belt Blower','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'V - Belt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'Motor Exhaust','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'Motor Blower','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'Motor Gear Box','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'Motor Gear Box Meja','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'Rantai Meja','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'Rantai Roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'Roll Overfeed (miki ppully)','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>7,'name' => 'Filter Blower','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['machine_group_id'=>16,'name' => 'Steam box','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Motor Gear Box Feeder','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Expander Cigar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Motor Gear Box Expander','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Felt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Telfon Sheet Felt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Roll Loadcell 1 & 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Motor Gear Box Roll Felt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Bearing Roll Felt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Rotary Joint Heating 1 & 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Flexible Steam','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Saluran Pembuangan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Valve Input Steam','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Steam Box 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Conveyor Flaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Motor Gear Box Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Rantai Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Bush Guider Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Motor g.b. up-down table','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Selang Angin','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>16,'name' => 'Regulator','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['machine_group_id'=>17,'name' => 'Steam box','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Motor Gear Box Feeder','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Expander Cigar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Motor Gear Box Expander','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Felt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Telfon Sheet Felt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Roll Loadcell 1 & 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Motor Gear Box Roll Felt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Bearing Roll Felt','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Rotary Joint Heating 1 & 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Flexible Steam','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Saluran Pembuangan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Valve Input Steam','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Steam Box 2','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Conveyor Flaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Motor Gear Box Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Rantai Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Bush Guider Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Motor g.b. up-down table','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Selang Angin','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>17,'name' => 'Regulator','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['machine_group_id'=>10,'name' => 'Motor Gear Box Plate','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>10,'name' => 'Motor Gear Box Cylinder','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>10,'name' => 'Level','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>10,'name' => 'Gear Box Roll Press','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>10,'name' => 'Pneumatic Roll Press','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>10,'name' => 'Rantai Gear Box','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>10,'name' => 'Rotary joint','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>10,'name' => 'Flexible Hose','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>10,'name' => 'Bearing Cylinder','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>10,'name' => 'Steam Valve','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['machine_group_id'=>13,'name' => 'Conveyor Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>13,'name' => 'Roll Conveyor','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>13,'name' => 'Bearing Roll Conveyor','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>13,'name' => 'Gear Box Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>13,'name' => 'Rantai Gear Box','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>13,'name' => 'Dancing Roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>13,'name' => 'Roll Obat','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>13,'name' => 'Roll Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>13,'name' => 'Detwisher','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>13,'name' => 'Turn Table','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['machine_group_id'=>14,'name' => 'Conveyor Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>14,'name' => 'Roll Conveyor','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>14,'name' => 'Bearing Roll Conveyor','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>14,'name' => 'Gear Box Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>14,'name' => 'Rantai Gear Box','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>14,'name' => 'Dancing Roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>14,'name' => 'Roll Obat','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>14,'name' => 'Roll Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>14,'name' => 'Detwisher','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>14,'name' => 'Turn Table','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['machine_group_id'=>15,'name' => 'Conveyor Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>15,'name' => 'Roll Conveyor','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>15,'name' => 'Bearing Roll Conveyor','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>15,'name' => 'Gear Box Plaiter','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>15,'name' => 'Rantai Gear Box','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>15,'name' => 'Dancing Roll','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>15,'name' => 'Roll Obat','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>15,'name' => 'Roll Penghantar','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>15,'name' => 'Detwisher','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['machine_group_id'=>15,'name' => 'Turn Table','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
        ];
        
        Model::insert($data);
    }
}
