<?php

namespace Modules\HumanResource\Database\seeds;

use Illuminate\Database\Seeder;
use Modules\HumanResource\Models\Position as Model;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();
        $data = [
            ['id'=>999,'parent_id'=>0,'code'=>'UD','name'=>'Undefined','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>1,'parent_id'=>0,'code'=>'BOD','name'=>'Board Of Director','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>2,'parent_id'=>1,'code'=>'MR-QMS','name'=>'Manajemen Representatif','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>3,'parent_id'=>2,'code'=>'STF-DCR-QMS','name'=>'Document Controller','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>4,'parent_id'=>1,'code'=>'KDP-HRGA','name'=>'Kepala Departemen HRGA','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>5,'parent_id'=>4,'code'=>'STF-HRD-HRGA','name'=>'Staff HRD','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>6,'parent_id'=>5,'code'=>'STF-SCT-HRGA','name'=>'Security','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>7,'parent_id'=>6,'code'=>'OP-SCT-HRGA','name'=>'Portier','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>8,'parent_id'=>4,'code'=>'STF-GA-HRGA','name'=>'Staff General Affair','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>9,'parent_id'=>4,'code'=>'KRD-SPL-HRGA','name'=>'Koordinator Sipil','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>10,'parent_id'=>9,'code'=>'STF-SPL-HRGA','name'=>'Staff Sipil','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>11,'parent_id'=>8,'code'=>'KR-PU-HRGA','name'=>'Kepala Regu Perbantuan Umum','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>12,'parent_id'=>8,'code'=>'WK-PU-HRGA','name'=>'Wakil Kepala Regu Perbantuan Umum','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>13,'parent_id'=>11,'code'=>'OP-PU-HRGA','name'=>'Operator Perbantuan Umum','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>14,'parent_id'=>9,'code'=>'ADM-SPL-HRGA','name'=>'Admin Sipil','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>15,'parent_id'=>4,'code'=>'ADM-HRGA','name'=>'Admin HRGA','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>16,'parent_id'=>1,'code'=>'KDP-FNA','name'=>'Kepala Departemen Finance & Accounting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>17,'parent_id'=>16,'code'=>'STF-FIN-FNA','name'=>'Staff Finance','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>18,'parent_id'=>16,'code'=>'STF-ACC-FNA','name'=>'Staff Accounting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>19,'parent_id'=>16,'code'=>'STF-PJK-FNA','name'=>'Staff Pajak','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>20,'parent_id'=>1,'code'=>'MGR-ENG','name'=>'Manager Engineering','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>21,'parent_id'=>20,'code'=>'KDP-ZB-ENG','name'=>'Kepala Departemen Zona Basah','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>22,'parent_id'=>20,'code'=>'KDP-ZK-ENG','name'=>'Kepala Departemen Zona Kering','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>23,'parent_id'=>20,'code'=>'KDP-BO-ENG','name'=>'Kepala Departemen Bengkel Otomotif','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>24,'parent_id'=>21,'code'=>'STF-ZB-ENG','name'=>'Staff Zona Basah','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>25,'parent_id'=>22,'code'=>'STF-ZK-ENG','name'=>'Staff Zona Kering','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>26,'parent_id'=>20,'code'=>'STF-BO-ENG','name'=>'Staff Bengkel Otomotif','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>27,'parent_id'=>24,'code'=>'OP-ZB-ENG','name'=>'Operator Zona Basah','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>28,'parent_id'=>25,'code'=>'OP-ZK-ENG','name'=>'Operator Zona Kering','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>29,'parent_id'=>26,'code'=>'OP-BO-ENG','name'=>'Operator Bengkel Otomotif','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>30,'parent_id'=>1,'code'=>'KDP-IT','name'=>'Kepala Departemen IT','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>31,'parent_id'=>30,'code'=>'STF-SFW-IT','name'=>'Staff Software','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>32,'parent_id'=>30,'code'=>'STF-HRW-IT','name'=>'Staff Hardware','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>33,'parent_id'=>1,'code'=>'KDP-MKT-MKT','name'=>'Kepala Departemen Marketing','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>34,'parent_id'=>33,'code'=>'STF-MKT-MKT','name'=>'Staff Marketing','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>35,'parent_id'=>34,'code'=>'ADM-MKT-MKT','name'=>'Admin Marketing','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>36,'parent_id'=>1,'code'=>'MGR-PPIC','name'=>'Manager PPIC','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>37,'parent_id'=>36,'code'=>'KDP-PPC-PPIC','name'=>'Kepala Departemen PPC','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>38,'parent_id'=>37,'code'=>'STF-PLN-PPC','name'=>'Staff Planning PPC','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>39,'parent_id'=>37,'code'=>'STF-PPCE-PPC','name'=>'Staff PPC Online Celup','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>40,'parent_id'=>37,'code'=>'STF-PPCA-PPC','name'=>'Staff PPC Online Calender','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>41,'parent_id'=>37,'code'=>'OP-FAL-PPC','name'=>'Operator Follow Up Lapangan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>42,'parent_id'=>36,'code'=>'KDP-EKS-PPIC','name'=>'Kepala Departemen Ekspedisi','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>43,'parent_id'=>42,'code'=>'STF-EKS','name'=>'Staff Ekspedisi','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>44,'parent_id'=>43,'code'=>'SPR-EKS','name'=>'Supir','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>45,'parent_id'=>42,'code'=>'KNT-EKS','name'=>'Kernet','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>46,'parent_id'=>36,'code'=>'KDP-IC-PPIC','name'=>'Kepala Departemen Inventory Control','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>47,'parent_id'=>46,'code'=>'KPL-GDG-IC','name'=>'Kepala Gudang Greige','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>48,'parent_id'=>47,'code'=>'KS-PGR-GDG','name'=>'Kepala Shift Penerimaan Greige','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>49,'parent_id'=>47,'code'=>'KS-PMT-GBJ','name'=>'Kepala Shift Pemartaian','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>50,'parent_id'=>46,'code'=>'ADM-GDG-IC','name'=>'Admin Gudang Greige','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>51,'parent_id'=>48,'code'=>'KR-PGR-GDG','name'=>'Kepala Regu Penerimaan Greige','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>52,'parent_id'=>51,'code'=>'OP-PGR-GDG','name'=>'Operator Penerimaan Greige','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>53,'parent_id'=>49,'code'=>'KR-PMT-GDG','name'=>'Kepala Regu Pemartaian','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>54,'parent_id'=>53,'code'=>'OP-PMT-GDG','name'=>'Operator Pemartaian','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>55,'parent_id'=>46,'code'=>'KPL-GBJ-IC','name'=>'Kepala Gudang Barang Jadi','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>56,'parent_id'=>55,'code'=>'OP-GBJ-IC','name'=>'Operator Gudang Barang Jadi','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>57,'parent_id'=>46,'code'=>'KPL-GDO-IC','name'=>'Kepala Gudang Obat','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>58,'parent_id'=>57,'code'=>'KR-GDO-IC','name'=>'Kepala Regu Gudang Obat','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>59,'parent_id'=>58,'code'=>'OP-GDO-IC','name'=>'Operator Gudang Obat','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>60,'parent_id'=>46,'code'=>'KPL-GDU-IC','name'=>'Kepala Gudang Umum','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>61,'parent_id'=>60,'code'=>'STF-GDU-IC','name'=>'Staff Gudang Umum','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>62,'parent_id'=>60,'code'=>'ADM-GDU-IC','name'=>'Admin Gudang Umum','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>63,'parent_id'=>1,'code'=>'GM-OPS','name'=>'General Manager Operasional','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>64,'parent_id'=>63,'code'=>'MGR-MPRD','name'=>'Manager Produksi','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>65,'parent_id'=>64,'code'=>'KDP-PRD','name'=>'Kepala Departemen Produksi','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>66,'parent_id'=>65,'code'=>'KRD-DYE-PRD','name'=>'Koordinator Dyeing','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>67,'parent_id'=>66,'code'=>'KS-CNT-DYE','name'=>'Kepala Shift Continuous','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>68,'parent_id'=>67,'code'=>'KR-CNT-DYE','name'=>'Kepala Regu Continuous','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>69,'parent_id'=>67,'code'=>'WKR-CNT-DYE','name'=>'Wakil Kepala Regu Continuous','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>70,'parent_id'=>68,'code'=>'OP-CNT-DYE','name'=>'Operator Continuous','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>71,'parent_id'=>66,'code'=>'KS-CLW-DYE','name'=>'Kepala Shift Celup Warna','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>72,'parent_id'=>71,'code'=>'KR-CLW-DYE','name'=>'Kepala Regu Celup Warna','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>73,'parent_id'=>71,'code'=>'WKR-CLW-DYE','name'=>'Wakil Kepala Regu Celup Warna','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>74,'parent_id'=>72,'code'=>'OP-CLW-DYE','name'=>'Operator Celup Warna','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>75,'parent_id'=>66,'code'=>'KS-TO-DYE','name'=>'Kepala Shift Timbang Obat','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>76,'parent_id'=>75,'code'=>'KR-TO-DYE','name'=>'Kepala Regu Timbang Obat','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>77,'parent_id'=>76,'code'=>'OP-TO-DYE','name'=>'Operator Timbang Obat','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>78,'parent_id'=>66,'code'=>'KS-CLH-DYE','name'=>'Kepala Shift Celup Haspel','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>79,'parent_id'=>78,'code'=>'KR-CLH-DYE','name'=>'Kepala Regu Celup Haspel','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>80,'parent_id'=>79,'code'=>'OP-CLH-DYE','name'=>'Operator Celup Haspel','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>81,'parent_id'=>66,'code'=>'KS-MCZ-DYE','name'=>'Kepala Shift Mercerized','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>82,'parent_id'=>81,'code'=>'KR-MCZ-DYE','name'=>'Kepala Regu Mercerized','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>83,'parent_id'=>82,'code'=>'OP-MCZ-DYE','name'=>'Operator Mercerized','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>84,'parent_id'=>65,'code'=>'KRD-FSH-PRD','name'=>'Koordinator Finishing','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>85,'parent_id'=>84,'code'=>'KS-CDD-FSH','name'=>'Kepala Shift Calator/Dryer Depan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>86,'parent_id'=>85,'code'=>'KR-CDD-FSH','name'=>'Kepala Regu Calator/Dryer Depan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>87,'parent_id'=>86,'code'=>'OP-CD-FSH','name'=>'Operator Calator Depan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>88,'parent_id'=>86,'code'=>'OP-DD-FSH','name'=>'Operator Dryer Depan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>89,'parent_id'=>84,'code'=>'KS-CLL-FSH','name'=>'Kepala Shift Callender','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>90,'parent_id'=>89,'code'=>'KR-CLL-FSH','name'=>'Kepala Regu Callender','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>91,'parent_id'=>90,'code'=>'OP-CLL-FSH','name'=>'Operator Callender','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>92,'parent_id'=>84,'code'=>'KS-CDB-FSH','name'=>'Kepala Shift Calator/Dryer Belakang','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>93,'parent_id'=>92,'code'=>'KR-CDB-FSH','name'=>'Kepala Regu Calator/Dryer Belakang','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>94,'parent_id'=>93,'code'=>'OP-CB-FSH','name'=>'Operator Calator Belakang','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>95,'parent_id'=>93,'code'=>'OP-DB-FSH','name'=>'Operator Dryer Belakang','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>96,'parent_id'=>84,'code'=>'KS-SET-FSH','name'=>'Kepala Shift Setting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>97,'parent_id'=>96,'code'=>'KR-SET-FSH','name'=>'Kepala Regu Setting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>98,'parent_id'=>97,'code'=>'OP-SET-FSH','name'=>'Operator Setting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>99,'parent_id'=>84,'code'=>'KS-FNS-FSH','name'=>'Kepala Shift Finish','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>100,'parent_id'=>99,'code'=>'KR-FNS-FSH','name'=>'Kepala Regu Finish','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>101,'parent_id'=>100,'code'=>'OP-FNS-FSH','name'=>'Operator Finish','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>102,'parent_id'=>65,'code'=>'KS-INS-FSH','name'=>'Kepala Shift Inspekting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>103,'parent_id'=>102,'code'=>'KR-INS-FSH','name'=>'Kepala Regu Inspekting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>104,'parent_id'=>102,'code'=>'WKR-INS-FSH','name'=>'Wakil Kepala Regu Inspekting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>105,'parent_id'=>65,'code'=>'ADM-PRD','name'=>'Admin Produksi','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>106,'parent_id'=>1,'code'=>'KDP-UTW-MPRD','name'=>'Kepala Departemen Utility + WWTP','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>107,'parent_id'=>106,'code'=>'KS-UTI-UTW','name'=>'Kepala Shift Utility','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>108,'parent_id'=>107,'code'=>'KR-UTI-UTW','name'=>'Kepala Regu Utility','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>109,'parent_id'=>108,'code'=>'OP-UTI-UTW','name'=>'Operator Utility','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>110,'parent_id'=>107,'code'=>'KR-BOI-UTI','name'=>'Kepala Regu Boiler','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>111,'parent_id'=>110,'code'=>'OP-BOI-UTI','name'=>'Operator Boiler','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>112,'parent_id'=>106,'code'=>'KS-WWTP-UTW','name'=>'Kepala Shift WWTP','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>113,'parent_id'=>112,'code'=>'KR-WWTP-UTW','name'=>'Kepala Regu WWTP','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>114,'parent_id'=>113,'code'=>'OP-WWTP-UTW','name'=>'Operator WWTP','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>115,'parent_id'=>1,'code'=>'MGR-MLAB','name'=>'Manager Lab','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>116,'parent_id'=>115,'code'=>'KDP-RND-LAB','name'=>'Kepala Departemen R&D','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>117,'parent_id'=>116,'code'=>'STF-RND-LAB','name'=>'Staff R&D','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>118,'parent_id'=>116,'code'=>'ADM-RND-LAB','name'=>'Admin R&D','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>119,'parent_id'=>115,'code'=>'KDP-QC-LAB','name'=>'Kepala Departemen Quality Control','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>120,'parent_id'=>119,'code'=>'KS-QC-LAB','name'=>'Kepala Shift Quality Control','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>121,'parent_id'=>120,'code'=>'KR-QCD-QC','name'=>'Kepala Regu QC Depan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>122,'parent_id'=>121,'code'=>'OP-QCD-QC','name'=>'Kepala Regu QC Depan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>123,'parent_id'=>119,'code'=>'KR-QCT-QC','name'=>'Kepala Regu QC Timur','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>124,'parent_id'=>123,'code'=>'OP-QCT-QC','name'=>'Kepala Regu QC Timur','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>125,'parent_id'=>119,'code'=>'KR-QCS-QC','name'=>'Kepala Regu QC Setting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>126,'parent_id'=>125,'code'=>'OP-QCS-QC','name'=>'Kepala Regu QC Setting','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>127,'parent_id'=>119,'code'=>'KR-RTR-QC','name'=>'Kepala Regu Returan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>128,'parent_id'=>127,'code'=>'OP-RTR-QC','name'=>'Operator Returan','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>129,'parent_id'=>115,'code'=>'KDP-LAB-MLAB','name'=>'Kepala Departemen Lab','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>130,'parent_id'=>129,'code'=>'STF-PRS-LAB','name'=>'Staff Proses Lab','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>131,'parent_id'=>130,'code'=>'KS-PRS-LAB','name'=>'Kepala Shift Proses Lab','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>132,'parent_id'=>131,'code'=>'ADM-PRS-LAB','name'=>'Admin Proses Lab','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>133,'parent_id'=>131,'code'=>'OP-PRS-LAB','name'=>'Operator Proses Lab','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>134,'parent_id'=>129,'code'=>'STF-LAB','name'=>'Staff Lab','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>135,'parent_id'=>134,'code'=>'ADM-LAB','name'=>'Admin Lab','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>136,'parent_id'=>134,'code'=>'OP-LAB','name'=>'Operator Lab','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>137,'parent_id'=>1,'code'=>'KDP-PMB','name'=>'Kepala Departemen Pembelian','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>138,'parent_id'=>137,'code'=>'STF-PMB','name'=>'Staff Pembelian','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>139,'parent_id'=>138,'code'=>'ADM-PMB','name'=>'Admin Pembelian','created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now]
        ];

        Model::insert($data);
    }
}
