<?php

namespace Modules\Engineering\Database\seeds;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Modules\Engineering\Models\Machine as Model;

class MachineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();
        $data = [
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'A','code'=>'JF-A-1','description'=>null,'serial_number'=>'TSH 13110','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'November 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'A','code'=>'JF-A-2','description'=>null,'serial_number'=>'TSH 13109','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'November 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'A','code'=>'JF-A-3','description'=>null,'serial_number'=>'TSH 13108','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'November 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'A','code'=>'JF-A-4','description'=>null,'serial_number'=>'TSH 13088','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'August 2013','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'A','code'=>'JF-A-5','description'=>null,'serial_number'=>'TSH 13089','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'August 2013','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'A','code'=>'JF-A-6','description'=>null,'serial_number'=>'TSH 12127','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'June 2013','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-1','description'=>null,'serial_number'=>'S 15513','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'February 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-2','description'=>null,'serial_number'=>'S 15514','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'February 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-3','description'=>null,'serial_number'=>'S 15511','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'February 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-4','description'=>null,'serial_number'=>'S 15515','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'February 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-5','description'=>null,'serial_number'=>'S 15512','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'February 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-6','description'=>null,'serial_number'=>'S 15516','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'February 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-7','description'=>null,'serial_number'=>'S 15506','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'January 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-8','description'=>null,'serial_number'=>'S 15507','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'January 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-9','description'=>null,'serial_number'=>'S 15505','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'January 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-10','description'=>null,'serial_number'=>'S 15509','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'January 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-11','description'=>null,'serial_number'=>'S 15504','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'January 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-12','description'=>null,'serial_number'=>'S 15508','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'January 2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-13','description'=>null,'serial_number'=>'K 15531','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'May 2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-14','description'=>null,'serial_number'=>'K 15532','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'May 2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-15','description'=>null,'serial_number'=>'K 15530','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'May 2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-16','description'=>null,'serial_number'=>'K 15534','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'May 2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-17','description'=>null,'serial_number'=>'K 15535','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'May 2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'B','code'=>'JF-B-18','description'=>null,'serial_number'=>'K 15526','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'May 2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-1','description'=>null,'serial_number'=>'TSH 14049','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'March 2014','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-2','description'=>null,'serial_number'=>'TSH 14018','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'March 2014','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-3','description'=>null,'serial_number'=>'3211 HF','brand'=>'SCLAVOS S.A.','type'=>null,'year'=>'2013','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-4','description'=>null,'serial_number'=>'K 15528','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'May 2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-5','description'=>null,'serial_number'=>null,'brand'=>'TONGGENG','type'=>'TGRU – ROR – 800','year'=>'2008','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-6','description'=>null,'serial_number'=>'SM 17188','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2017','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-7','description'=>null,'serial_number'=>'SM 17189','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2017','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-8','description'=>null,'serial_number'=>'SM 17190','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2017','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-9','description'=>null,'serial_number'=>'SM 17191','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2017','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-10','description'=>null,'serial_number'=>'K 15527','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-11','description'=>null,'serial_number'=>'SM 17192','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2017','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-12','description'=>null,'serial_number'=>'SM 17193','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2017','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-13','description'=>null,'serial_number'=>'SM 17203','brand'=>'CANLAR ','type'=>'FABRIC DYEING','year'=>'2018','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-14','description'=>null,'serial_number'=>'S 16700','brand'=>'CANLAR ','type'=>'FABRIC DYEING','year'=>'2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-15','description'=>null,'serial_number'=>'S 16701','brand'=>'CANLAR ','type'=>'FABRIC DYEING','year'=>'2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-16','description'=>null,'serial_number'=>'S 16702','brand'=>'CANLAR ','type'=>'FABRIC DYEING','year'=>'2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'C','code'=>'JF-C-17','description'=>null,'serial_number'=>'S 16703','brand'=>'CANLAR ','type'=>'FABRIC DYEING','year'=>'2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-1','description'=>null,'serial_number'=>'1455','brand'=>'AKM','type'=>'03378 M','year'=>'2005','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-2','description'=>null,'serial_number'=>'19052','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1989','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-3','description'=>null,'serial_number'=>'30895','brand'=>'THIES','type'=>'D 49653 COSFELD','year'=>'1996','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-4','description'=>null,'serial_number'=>'2984','brand'=>'THIES','type'=>'D 48651 COSFELD','year'=>'1995','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-5','description'=>null,'serial_number'=>'29664','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1995','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-6','description'=>null,'serial_number'=>'21532','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1989','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-7','description'=>null,'serial_number'=>'19465','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1988','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-8','description'=>null,'serial_number'=>null,'brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1995','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-9','description'=>null,'serial_number'=>null,'brand'=>'AKM','type'=>'AK – REO 2T','year'=>'2003','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-10','description'=>null,'serial_number'=>'21119','brand'=>'AKM','type'=>'AK – REO 2T','year'=>'2003','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-11','description'=>null,'serial_number'=>'TSH 14016','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'March 2014','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-12','description'=>null,'serial_number'=>'TSH 14017','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'March 2014','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-13','description'=>null,'serial_number'=>'S 16706','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-14','description'=>null,'serial_number'=>'S 16707','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-15','description'=>null,'serial_number'=>'K 15530','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'May 2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-16','description'=>null,'serial_number'=>'K 15529','brand'=>'CANLAR','type'=>'HT. TECH SOFT H.','year'=>'May 2015','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-17','description'=>null,'serial_number'=>'26344','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1993','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-18','description'=>null,'serial_number'=>'S 16704','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-19','description'=>null,'serial_number'=>'S 16705','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'D','code'=>'JF-D-20','description'=>null,'serial_number'=>null,'brand'=>'AKM','type'=>'AK- HTO 75','year'=>'2005','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-1','description'=>null,'serial_number'=>'21146','brand'=>'AKM','type'=>'AK-R004','year'=>'2008','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-2','description'=>null,'serial_number'=>'21134','brand'=>'AKM','type'=>'AK-R004','year'=>'2008','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-3','description'=>null,'serial_number'=>'28017','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1994','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-4','description'=>null,'serial_number'=>'28019','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1994','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-5','description'=>null,'serial_number'=>'24840','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1992','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-6','description'=>null,'serial_number'=>'24850','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1992','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-7','description'=>null,'serial_number'=>'27054','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1993','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-8','description'=>null,'serial_number'=>'26593','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1993','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-9','description'=>null,'serial_number'=>'29891','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1995','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-10','description'=>null,'serial_number'=>'69934','brand'=>'THEN','type'=>'AFS 450','year'=>'1996','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-11','description'=>null,'serial_number'=>null,'brand'=>'KTH','type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-12','description'=>null,'serial_number'=>'28514','brand'=>'THIES','type'=>'D 4851 COSFELD','year'=>'1990','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-13','description'=>null,'serial_number'=>'22616','brand'=>'THIES','type'=>'COSFELD BRD','year'=>'1990','is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'E','code'=>'JF-E-14','description'=>null,'serial_number'=>'23241','brand'=>'THIES','type'=>'COSFELD BRD','year'=>'1990','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-1','description'=>null,'serial_number'=>'22190','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1990','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-2','description'=>null,'serial_number'=>'22167','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1990','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-3','description'=>null,'serial_number'=>'22164','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1990','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-4','description'=>null,'serial_number'=>'-','brand'=>'SCLAVOS','type'=>'-','year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-5','description'=>null,'serial_number'=>'S 15517','brand'=>'CANLAR','type'=>'FABRIC DYEING','year'=>'2016','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-6','description'=>null,'serial_number'=>'49604','brand'=>'THIES','type'=>'D 48653 COSFELD','year'=>'2006','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-7','description'=>null,'serial_number'=>'28011','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1994','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-8','description'=>null,'serial_number'=>'25775','brand'=>'THIES','type'=>'D 4420 COSFELD','year'=>'1992','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-9','description'=>null,'serial_number'=>null,'brand'=>'KTH','type'=>null,'year'=>'2002','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-10','description'=>null,'serial_number'=>null,'brand'=>'KTH','type'=>null,'year'=>'2002','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-11','description'=>null,'serial_number'=>null,'brand'=>'KTH','type'=>null,'year'=>'2002','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-12','description'=>null,'serial_number'=>null,'brand'=>'KTH','type'=>null,'year'=>'2004','is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            // ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-13','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            // ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-14','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            // ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-15','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            // ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-16','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            // ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-17','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            // ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'JF','note' => 'F','code'=>'JF-F-18','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CTS','note' => 'Herbatex','code'=>'CTS-HBTX-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CTS','note' => 'Herbatex','code'=>'CTS-HBTX-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CTS','note' => 'Santex','code'=>'CTS-STX-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CTS','note' => 'Santex','code'=>'CTS-STX-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'MCR','note' => 'Dornier','code'=>'MCR-DRNR-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'MCR','note' => 'Dornier','code'=>'MCR-DRNR-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'MCR','note' => 'Dornier','code'=>'MCR-DRNR-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'MCR','note' => 'Dornier','code'=>'MCR-DRNR-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'MCR','note' => 'Dornier','code'=>'MCR-DRNR-5','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'MCR','note' => 'Dornier','code'=>'MCR-DRNR-6','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'MCR','note' => 'Dornier','code'=>'MCR-DRNR-7','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'MCR','note' => 'Dornier','code'=>'MCR-DRNR-8','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'MCR','note' => 'Sando','code'=>'MCR-SDO-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'NTRL-MCR','note' => null,'code'=>'NTRL-MCR-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'NTRL-MCR','note' => null,'code'=>'NTRL-MCR-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Depan','code'=>'CLT-DPN-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Depan','code'=>'CLT-DPN-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Depan','code'=>'CLT-DPN-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Timur','code'=>'CLT-TMR-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Timur','code'=>'CLT-TMR-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Timur','code'=>'CLT-TMR-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Timur','code'=>'CLT-TMR-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Belakang','code'=>'CLT-BLK-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Belakang','code'=>'CLT-BLK-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Belakang','code'=>'CLT-BLK-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
			['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Belakang','code'=>'CLT-BLK-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
			['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Belakang','code'=>'CLT-BLK-5','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLT','note' => 'Belakang','code'=>'CLT-BLK-6','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'DRY','note' => 'Santex','code'=>'DRY-STX-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'DRY','note' => 'Santex','code'=>'DRY-STX-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'DRY','note' => 'Intex','code'=>'DRY-ITX-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'DRY','note' => 'Intex','code'=>'DRY-ITX-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'DRY','note' => 'Intex','code'=>'DRY-ITX-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLD-DRY','note' => null,'code'=>'CLD-DRY-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLD-DRY','note' => null,'code'=>'CLD-DRY-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
			['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLD-DRY','note' => null,'code'=>'CLD-DRY-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CLD-DRY','note' => null,'code'=>'CLD-DRY-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SET','note' => 'Dongnam','code'=>'SET-DNM-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SET','note' => 'Dongnam','code'=>'SET-DNM-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SET','note' => 'Dongnam','code'=>'SET-DNM-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SET','note' => 'SMM','code'=>'SET-SMM-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SET','note' => 'SMM','code'=>'SET-SMM-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SET','note' => 'SMM','code'=>'SET-SMM-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SET','note' => 'SMM','code'=>'SET-SMM-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SET','note' => 'Bitexma','code'=>'SET-BTX-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Depan','code'=>'CND-DPN-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Depan','code'=>'CND-DPN-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Depan','code'=>'CND-DPN-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
			['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Depan','code'=>'CND-DPN-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Depan','code'=>'CND-DPN-5','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Timur','code'=>'CND-TMR-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Timur','code'=>'CND-TMR-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Timur','code'=>'CND-TMR-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
			['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Timur','code'=>'CND-TMR-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CND','note' => 'Timur','code'=>'CND-TMR-5','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'FNS','note' => null,'code'=>'FNS-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'FNS','note' => null,'code'=>'FNS-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Fiber','code'=>'CP-FBR-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Fiber','code'=>'CP-FBR-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Fiber','code'=>'CP-FBR-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Fiber','code'=>'CP-FBR-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Fiber','code'=>'CP-FBR-5','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Fiber','code'=>'CP-FBR-6','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Fiber','code'=>'CP-FBR-7','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Stainless','code'=>'CP-STNS-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Stainless','code'=>'CP-STNS-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Stainless','code'=>'CP-STNS-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Stainless','code'=>'CP-STNS-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Stainless','code'=>'CP-STNS-5','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Stainless','code'=>'CP-STNS-6','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Stainless','code'=>'CP-STNS-7','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Haspel','code'=>'CP-HPL-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Haspel','code'=>'CP-HPL-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Netral','code'=>'CP-NTR-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'CP','note' => 'Netral','code'=>'CP-NTR-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-1','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-2','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-3','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-4','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-5','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-6','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-7','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-8','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-9','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-10','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-11','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-12','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-13','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-14','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-15','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-16','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'INSP','note'=>null,'code'=>'INSP-17','description'=>null,'serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 0,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SRV','note'=>null,'code'=>'SRV-BK','description'=>'Belah kain','serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SRV','note'=>null,'code'=>'SRV-CS','description'=>'Colour service','serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SRV','note'=>null,'code'=>'SRV-XB','description'=>'Xinbow','serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SRV','note'=>null,'code'=>'SRV-RC','description'=>'Recovery Caustic','serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SRV','note'=>null,'code'=>'SRV-CMP','description'=>'COMPRESSOR','serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SRV','note'=>null,'code'=>'SRV-GS','description'=>'Genset','serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],
            ['id'=>Str::uuid(),'machine_area_code'=>'PRD','machine_group_code'=>'SRV','note'=>null,'code'=>'SRV-LAB','description'=>'LAB','serial_number'=>null,'brand'=>null,'type'=>null,'year'=>null,'is_active' => 1,'created_by'=>1,'updated_by'=>1,'created_at'=>$now,'updated_at'=>$now],

            
        ];
        
        Model::insert($data);
    }

    public function read()
    {
        $file = public_path('machines.csv');

        $models = $this->csvToArray($file, ';');

        foreach($models as $model){
            $machineBrand = \Modules\Engineering\Models\MachineBrand::where('name', $model['brand'])->first();
            $machineType = \Modules\Engineering\Models\MachineType::where('name', $model['type'])->first();
            echo "['machine_brand_id'=>'".($machineBrand ? $machineBrand->id : '')."', 'machine_type_id'=>'".($machineType ? $machineType->id : '')."', 'code'=>'".$model['code']."','area' => '".$model['area']."','year' => '".$model['year']."', 'is_active' => 1, 'created_by'=>1,'updated_by'=>1,'created_at'=>\$now,'updated_at'=>\$now],\n";
        }
    }

    function csvToArray($filename = '', $delimiter = ',')
    {
        if (!file_exists($filename) || !is_readable($filename))
            return false;

        $header = null;
        $data = array();
        if (($handle = fopen($filename, 'r')) !== false)
        {
            while (($row = fgetcsv($handle, 1000, $delimiter)) !== false)
            {
                if (!$header)
                    $header = $row;
                else
                    $data[] = array_combine($header, $row);
            }
            fclose($handle);
        }

        return $data;
    }
}
